services:
  redis:
    container_name: content-management-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - content-management-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  content-management-network:
    driver: bridge
